name: Test Makefile

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Makefile
      run: make
      
    - name: Run tests
      run: npm test
